[build]
target = "x86_64-solas_os.json"

# Allows you to build an iso and launch it via 'cargo run'
[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std          = ["core", "compiler_builtins"]
